### ISSUE TITLE
PSL does not show status of profession treasures

### ISSUE THREAD

**Issue by belg8rion** [Sluimerstand/ProfessionShoppingList#145]
PSL does not show status of profession treasures when hovering over perks unlocked in profession specialization.

I found this to be extremely useful and miss it :(

**Comment by Sluimerstand** [comment]
I've retired this particular feature, because it was very time-intensive to maintain and other addons do this better.

For the profession treasures in particular, [HandyNotes](https://www.curseforge.com/wow/addons/handynotes) + [HandyNotes: Dragonflight](https://www.curseforge.com/wow/addons/handynotes-dragonflight) or [All The Things](https://www.curseforge.com/wow/addons/all-the-things) can show the collection status of these and also includes their coordinates.

For profession weeklies, I'd recommend [Chore Tracker](https://www.curseforge.com/wow/addons/chore-tracker) by WowThing.org author Freddie. It's great!
