### ISSUE TITLE
Missing profession knowledge list

### ISSUE THREAD

**Issue by dblanch369** [Sluimerstand/ProfessionShoppingList#146]
The awesome little knowledge list of missing knowledge items was really helpful.  Will this be coming back? I wasn't done collecting DF locations on my alts, lol.

**Comment by Sluimerstand** [comment]
I've retired this particular feature, because it was very time-intensive to maintain and other addons do this better.

For the profession treasures in particular, [HandyNotes](https://www.curseforge.com/wow/addons/handynotes) + [HandyNotes: Dragonflight](https://www.curseforge.com/wow/addons/handynotes-dragonflight) or [All The Things](https://www.curseforge.com/wow/addons/all-the-things) can show the collection status of these and also includes their coordinates.

For profession weeklies, I'd recommend [Chore Tracker](https://www.curseforge.com/wow/addons/chore-tracker) by WowThing.org author Freddie. It's great!

**Comment by dblanch369** [comment]
Thank you for your honest answer, and suggestions.  I use Handynotes and All The Things, but yours was easier lol.   I appreciate the work you did for Dragonflight.  Take it easy!
