### ISSUE TITLE
Reagents window empty after switching characters

### ISSUE THREAD

**Issue by Starvoicereason** [Sluimerstand/ProfessionShoppingList#15]
I had a situation that caused me to delete my WTF folder and now Profession Shopping list is showing an empty reagent (but still populated Recipe list) when I get to a new character. Tracking a recipe from that Character adds those items to the reagent window, but nothing else shows up. Logging out of the character and back in presents me with an empty reagent window again.

**Comment by Sluimerstand** [comment]
Hm, that is odd. If you have deleted your WTF folder, both recipes _and_ reagents should have been reset.
Could you try the following and see if that resolves your issue?

- `/psl clear` and `/reload`
This should properly reset anything that is tracked and prevent the recipe and reagent info from deviating.

If that does not work:
- Delete both `ProfessionShoppingList.lua` and `ProfessionShoppingList.lua.bak` from your `World of Warcraft\_retail_\WTF\Account\YOURACCOUNT\SavedVariables` folder.
- Reinstall the AddOn.
This should completely reset the AddOn and make sure nothing went wrong when installing it.

If the issue still persists, I'll have to find a way to reproduce the issue so I can see what's actually happening.

**Comment by Sluimerstand** [comment]
Alright, this was actually a bug on my end caused by the subreagents feature.
I've fixed this now with the latest release, but removing recipes is now only possible when on a character with the profession that recipe is from. I hope to get that fixed next release.

**Comment by Starvoicereason** [comment]
Thanks. I love this thing, I spent the time until you fixed it clearing and re-adding everything on every alt! ^-^ Was perfectly willing to keep doing it, since this plus BagSync saves my sanity~! You do good work.

**Comment by Sluimerstand** [comment]
The sorting is a little weird. In order to get the item links in the tables it uses strings like this:
`"|cff0070dd|Hitem:23571::::::::60:63:::::::::|h[Primal Might]|h|r"`
The first bit is the colour, which is from the item's quality, then it goes by itemID. I haven't quite figured out yet how to make it sort in a more logical manner, because the library I use for the tables doesn't have a lot of documentation and I'm still a novice programmer. It's on the to do list to figure out how to do that! :D
Sorting by # should just be ascending or descending, yes.
