### ISSUE TITLE
Add ability to track Patron work order recipes and exclude materials included in the order

### ISSUE THREAD

**Issue by Vilsara** [Sluimerstand/ProfessionShoppingList#163]

**Comment by Sluimerstand** [comment]
Hello! Accounting for provided materials is something I wasn't able to do in Dragonflight, since the information provided for that is constructed in a super weird way that I've at least not yet been able to decipher, nor has anyone that also maintains the Warcraft Wiki (who are generally some super clever people).
It's been asked by other people as well though, so I will look into it and ask around when I have the time. :)

**Comment by glanotte** [comment]
perhaps if you could override the counts of materials manually? so you could do that while you were at the crafting table.

**Comment by Sluimerstand** [comment]
That is the intent, but I was under the impression that information was hard to come by and not easily available with the available API. Turns out I straight up lied and the information is readily available - I just somehow completely missed it!
I'll be adding support for this soon. :)

**Comment by Sluimerstand** [comment]
Okay the tricky part in the end was figuring out which order we're looking at without claiming it, so I could grab the necessary info. The amazing Plusmouse helped me out with this, and this will be included in the next release.
