### ISSUE TITLE
Ignore Warband for ShoppingList

### ISSUE THREAD

**Issue by Mursanian** [Sluimerstand/ProfessionShoppingList#186]
Add a Toggle to ignore all materials on the warband. (Especially handy for doing Patron Orders, as the crafting system does not pull from there. But the shopping list says mats are available.)

**Comment by Sluimerstand** [comment]
Hi @Mursanian, this toggle already exists:
![image](https://github.com/user-attachments/assets/bbbea5b5-4d8a-4c94-a11e-aa9df3fb7941)

It's attached to the bottom of the PSL window. When you generate the shopping list, it respects that setting.

**Comment by ergh99** [comment]
@Sluimerstand  This button seems to reset to checked every time the addon loads.  If this is the expected behavior, maybe consider changing this to a persistent setting.

**Comment by Sluimerstand** [comment]
@ergh99 This is intended behaviour, yes. The reason being that I wanted the default to be "all owned reagents", rather than "all usable reagents" because the latter is only relevant for crafting orders. A persistent setting would make more sense in a lot of cases, but I wanted to make sure people always first consider they can have items in the Warbank.

This feature will be removed with 11.0.5 next week anyway, since then we will be able to craft with items in the Warbank. :)

-----

So yes, by default PSL just ignores quality and tracks Tier 1 reagents. You can go into the addon's settings, and manually adjust this to be Tier 2 or Tier 3 for all reagents. (And you can adjust whether or not Tier 2 / Tier 3 reagents are counted when you are tracking Tier 1 reagents.)

Alternatively, you can simulate your crafts with CraftSim or TestFlight, and PSL will respect whatever qualities are set by these addons. :)
