### ISSUE TITLE
Button overlap with new CraftSim craft queue button

### ISSUE THREAD

**Issue by NoShotz** [Sluimerstand/ProfessionShoppingList#191]
![image](https://github.com/user-attachments/assets/a788fbe8-7031-40b1-b7f8-28a57c1dc1bd)

**Comment by Sluimerstand** [comment]
I don't mind moving buttons around in some cases since the profession UI has very limited space. I move one of my buttons out of the way for TestFlight and CraftScan, for example.

I will however not move the core buttons for my addon from the only place where they make sense to be.
Please take this issue over to the [CraftSim](https://github.com/derfloh205/CraftSim/issues) developer.
