### ISSUE TITLE
cooldown ready not accurate

### ISSUE THREAD

**Issue by chadmccune** [Sluimerstand/ProfessionShoppingList#196]
**AddOn version**
_For example v11.0.2-020

**Have you tried to /reload, used /psl clear if it is recipe-related, and checked the issue occurs with only PSL enabled?**
yes

**Have you taken a look at the addon's settings yet, to see if it's a feature that can be adjusted or disabled?**
yes

**Describe the problem**
Cooldowns that don't reset with the daily reset aren't accurate.  For example, Engineering Box o' Booms has a 24 hour cooldown, so if you make it at 3pm on Saturday, it's not available until 3pm Sunday.

**Comment by Sluimerstand** [comment]
@chadmccune Can you list which are not accurate for you, other than the Box o' Booms?
Due to the game returning the wrong information for cooldowns that are synced with daily reset, I need to manually put in the other ones to treat them correctly.
So far the ones that don't align with daily reset, that PSL has listed are: Alchemy experimentations, Invent, Algari Amber Prism

**Comment by chadmccune** [comment]
That's the only one I've noticed so far, I don't do a lot with my profession cooldowns atm
