### ISSUE TITLE
Hyperlinks not loading completely

### ISSUE THREAD

**Issue by LyaVanLou** [Sluimerstand/ProfessionShoppingList#23]
This is the "hiccup" I mentioned a while back on the ATT discord.

As seen in the screenshot, sometimes hyperlinks aren't loading completely. 
From what I've observed so far, it might be information not having been fully loaded before the windows get shown. (Waiting and toggling psl again after a bit will resolve it.)

![image](https://user-images.githubusercontent.com/56847157/201787270-141839f3-14a6-456a-b1fd-24d0c69611f1.png)

- [Google Doc with full Lua error](https://docs.google.com/document/d/1DYX2Lc5wiRZ1XHzzbknSV4G3kTWNr3IwSPhHI7a4yDU/edit?usp=sharing)

**Comment by Sluimerstand** [comment]
I do love me a good error report.

Have you used /psl clear since updating to the Dragonflight version yet? It's something I forgot to manage in the changelog, but because of some internal changes made that is necessary to keep it from bugging out. I'm not entirely sure this bug is related, but it may very well be since it seems to be having an issue parsing the itemlinks, which is one of the things I changed.

**Comment by LyaVanLou** [comment]
I just took a look again, to make sure I used /psl clear, but it persisted after that.

After some more testing and checking if other addons are interfering, I've found that I can reliably en- and disable this bug by turning on/off WoWthing Collector (V. 10.0.0.5). (With only psl, wowthing, bug grabber & bug sack enabled.)

**Comment by Sluimerstand** [comment]
Mm, odd. Any chance you can send me a copy of your `World of Warcraft\_retail_\WTF\Account\(AccountName)\SavedVariables\ProfessionShoppingList.lua` file? Then I can try to re-create the issue and see where the error lies exactly.

**Comment by Sluimerstand** [comment]
Issue should be resolved now!
