### ISSUE TITLE
Hard Crash when I enable this mod.

### ISSUE THREAD

**Issue by thebadmf** [Sluimerstand/ProfessionShoppingList#63]
Updated to Profession Shopping List v10.0.5-005) (2023-02-11) earlier and re-enabled the mod to see if it played any better with my setup. Unfortunately it'ss gotten worse hard crashed to oddesktop my wow every time anything profession related happened. DE item? Boom. Loot a weekly profession item? BAM! CTD. I disbaled the mod after the 5th crash is as many minutes and no more CTD's

I use Elvui, craftsim and many other mods, if there's anything i can do to help, please let me know.

**Comment by Sluimerstand** [comment]
Hey there. Do the crashes to desktop also occur when PSL is the only addon that is enabled?
Have you tried deleting the saved variables for the addon? (`World of Warcraft\_retail_\WTF\Account\(Account Name)\SavedVariables\ProfessionShoppingList.lua` and `ProfessionShoppingList.lua.bak`)

**Comment by thebadmf** [comment]
Hi I wouldn't ever run wow without my other addons. I'll tried deleting all the PSL variables. Went dirrt hunting and found the engineering core. As soon as I tried to learn it, CTD.

There were other issues which is why it was disabled in the first place, eg. whenever anything profession related was looted it would freeze and open the profession window.

**Comment by Sluimerstand** [comment]
Alright, so if it's not the saved variables, I suspect it's a combination of PSL and another specific addon that's causing the crashes.

That is why I asked whether or not the crashes occur with only PSL loaded - it's to test whether it is solely PSL that is at fault, or if it is the combination with another addon that is causing the crashes. (Since I cannot recreate the issue myself.)

**Comment by thebadmf** [comment]
I'll try and test on Monday

**Comment by Sluimerstand** [comment]
Alternatively I'd appreciate a list of AddOns you use, so I can try to recreate the issue myself. :)

**Comment by Sluimerstand** [comment]
@thebadmf In the `World of Warcraft\_retail_\Errors` folder should be a few .txt files created when the crashes to desktop occurred. When you have the time, could you send those? They can potentially tell me why it crashed through addon interactions.

**Comment by thebadmf** [comment]
Sorry been busy with family. Is there a way to DM on here? Can send my WTF and Interface folders

[Errors.zip](https://github.com/Sluimerstand/ProfessionShoppingList/files/10748292/Errors.zip)

**Comment by Sluimerstand** [comment]
Thank you for the error logs and no need to apologise! Unfortunately there is nothing in the error logs to indicate the crashes are being caused by addon interactions, even though enabling PSL clearly causes your game to crash to desktop.

As far as I know there is no way to DM on here, but we can chat on Discord so you can send/share me your WTF and Interface folders. If I can't recreate the issue then, it's likely PSL is somehow exacerbating an issue relating to your particular system setup that I unfortunately cannot assist with. Anyway, feel free to add me on Discord through: Sluimerstand#2370

**Comment by Sluimerstand** [comment]
I've played for several 1-2 hour sessions this week with your Interface and WTF folders, with all of your addons and settings, but I've not experienced a single crash. There is no way for me to reproduce the crashes to desktop on my system.

I do believe PSL is at least _part_ of the cause of your crashes, but at worst it would be exacerbating an underlying issue with your particular setup, as far as I can tell. It could be a compatibility issue with Windows 11, or a result of your system's long uptime, or some other factor, but I cannot for the life of me pinpoint what it is. Sorry that I am unable to help, but I suppose you're better off not using PSL. :(
